### ISSUE TITLE
Données du Dashboard côté backend

### ISSUE THREAD

**Issue by RomainCrevecoeur** [ABC-TransitionBasCarbone/clickson-api#45]
## Acceptance tests 

- [ ] Fonctionnality to test ?

## Test informations

- [ ] How to test this issue ?

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the `.github/ISSUE_TEMPLATE/template-feature.md` file to include the sections: Context, Acceptance tests, Test informations, and Technique Strategy as specified in the criteria.

You can review changes in this commit: https://github.com/lattaai13/ABC-TransitionBasCarbone-clickson-api-45/commit/696b3e33a9c59ba255daa055510aafdf26dc3a85.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
